Creeper Squids
PurpurMC/PurpurExtras pull request #57
Opened 2023-06-15 19:08 UTC by TheRealRyGuy

Lots of things configurable and to think about with this one 
- Do we want an explosion indicator? 
- Need to fix glitchy sounds when disengaging and re-engaging pathfinder + a proper re-engage for explosion ticks 
- What should be configurable? 
- Both Squid#setTarget and Pathfinder#findPath don't appear to actually be moving the Squid towards the player, tis a fun lil bug 

![Proof of concept](http://www.ryguy.me/share/19nOfEq3MC.mp4)
implements #48

2023-06-15 23:00 UTC, TheRealRyGuy commented
New config:
```
creeper-squid:
  enabled: true
  fuse-ticks: 30
  agro-distance: 7
  explosion-radius: 3
  velocity: 0.5
 ```
 Now properly sets velocity - rotation is a little wacky (#lookAt ends up horizontal as the eyes are on the side i guess?) 
 the vector math of velocity setting feels wrong but i live by the principle of if it ain't broke 

 Excuse the framey video but http://www.ryguy.me/share/vhyuLzNThx.mp4

2023-06-25 19:13 UTC, YouHaveTrouble requested changes

2023-06-25 19:13 UTC, YouHaveTrouble commented on src/main/java/org/purpurmc/purpurextras/modules/CreeperSquidsModule.java
> +                    playerDistance = p.getLocation().distance(squid.getLocation());
use distanceSquared instead of distance, less heavy way of doing this

2023-06-25 19:13 UTC, YouHaveTrouble commented on src/main/java/org/purpurmc/purpurextras/modules/CreeperSquidsModule.java
> +            if (currentTarget == null) {
invert and early return

2023-06-30 03:17 UTC, TheRealRyGuy commented
should be fixed up now - was a little confused on [this one](https://github.com/PurpurMC/PurpurExtras/pull/57#discussion_r1241265027) though, made an attempt nonetheless

2023-07-02 11:42 UTC, YouHaveTrouble approved these changes

2023-07-02 11:42 UTC, merged